- name: configure backend
  hosts: backend
  become: yes
  tasks:
  - name: dnf module disable nodejs -y
    ansible.builtin.command: dnf module disable nodejs -y

  - name:  dnf module enable nodejs:20 -y
    ansible.builtin.command:  dnf module enable nodejs:20 -y

  - name:   dnf install nodejs -y
    ansible.builtin.dnf:
      name: nodejs
      state: installed

  - name: useradd expense
    ansible.builtin.user: 
      name: expense    

  - name:  mkdir /app
    ansible.builtin.file:
      path: /app
      state: directory

  - name: curl -o and cd /app
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /app/
     
