- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_user: root
    login_host: db.narendra.shop
  vars_prompt:
    name: login_password 
    prompt: "Please enter password: ExpenseApp@1"
    private: false  
  tasks:
  - name: dnf install mysql-server -y
    ansible.builtin.dnf:
      name: mysql-server
      state: latest 

  - name: systemctl enable mysqld   
    ansible.builtin.service:
      name: mysqld 
      state: started 
      enabled: yes 

  - name: check password set or not
    community.mysql.mysql_info:    
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output      
        
