- name: configure frontend
  hosts: frontend
  become: yes
  tasks:
  - name: dnf install nginx -y 
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


  - name: delete default website
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download and extract frontend code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes 
      